### ISSUE TITLE
Suspicious List of TODO's for Kotti2.0.x

### ISSUE THREAD

**Issue by carsoli** [3YOURMIND/kotti#241]
- [ ] `jest.config.js` from old dir/ making sure tests are working under new build
- [x] figure a good way to add vue declarations ( we don't have shims now and we ts-ignore the vue imports for now); figure a way that doesn't conflict with the shims on any user-app (app that would import kotti) that uses vue and has the shims (duplicate shims file errors) 
- [x] find the proper type for the el-ui input elements that resulted from the hooks' queries and use it instead of the `HTMLInput*`; one fix for all 
- [x] `"FIXME"`s of el-ui types
- [x] kms

**Comment by FlorianWendelborn** [comment]
@carsoli I’ve split-off the first task from this into #306. Everything else is already solved as far as I can tell, which is great.
